
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.zeldaswordskillreborn.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.zeldaswordskillreborn.item.ZorasSapphireItem;
import net.mcreator.zeldaswordskillreborn.item.ZoraTunicItem;
import net.mcreator.zeldaswordskillreborn.item.ZeldasLullabyItem;
import net.mcreator.zeldaswordskillreborn.item.YellowRupeeItem;
import net.mcreator.zeldaswordskillreborn.item.WaterMedallionItem;
import net.mcreator.zeldaswordskillreborn.item.SunssongItem;
import net.mcreator.zeldaswordskillreborn.item.SpiritMedaillionItem;
import net.mcreator.zeldaswordskillreborn.item.SongofStormItem;
import net.mcreator.zeldaswordskillreborn.item.SongOfTimeItem;
import net.mcreator.zeldaswordskillreborn.item.SilverRupeeItem;
import net.mcreator.zeldaswordskillreborn.item.ShadowMedallionItem;
import net.mcreator.zeldaswordskillreborn.item.SerenadeofWaterItem;
import net.mcreator.zeldaswordskillreborn.item.SariassongItem;
import net.mcreator.zeldaswordskillreborn.item.RupeeWalletItem;
import net.mcreator.zeldaswordskillreborn.item.RequiemofSpiritsItem;
import net.mcreator.zeldaswordskillreborn.item.RedRupeeItem;
import net.mcreator.zeldaswordskillreborn.item.PurpleRupeeItem;
import net.mcreator.zeldaswordskillreborn.item.PreludeofLightItem;
import net.mcreator.zeldaswordskillreborn.item.OcarinaOfTimeItem;
import net.mcreator.zeldaswordskillreborn.item.NocturneofShadowItem;
import net.mcreator.zeldaswordskillreborn.item.MirrorShieldItem;
import net.mcreator.zeldaswordskillreborn.item.MinuetofForestItem;
import net.mcreator.zeldaswordskillreborn.item.MasterSwordItem;
import net.mcreator.zeldaswordskillreborn.item.LongshotItem;
import net.mcreator.zeldaswordskillreborn.item.LightMedallionItem;
import net.mcreator.zeldaswordskillreborn.item.KokiriTunicItem;
import net.mcreator.zeldaswordskillreborn.item.KokiriSwordItem;
import net.mcreator.zeldaswordskillreborn.item.KokiriEmerauldItem;
import net.mcreator.zeldaswordskillreborn.item.ItemMenuItem;
import net.mcreator.zeldaswordskillreborn.item.IronBootsItem;
import net.mcreator.zeldaswordskillreborn.item.HylianShieldItem;
import net.mcreator.zeldaswordskillreborn.item.HoverItem;
import net.mcreator.zeldaswordskillreborn.item.HookshotItem;
import net.mcreator.zeldaswordskillreborn.item.HammerItem;
import net.mcreator.zeldaswordskillreborn.item.GreenRupeeItem;
import net.mcreator.zeldaswordskillreborn.item.GoronTunicItem;
import net.mcreator.zeldaswordskillreborn.item.GoronRupeeItem;
import net.mcreator.zeldaswordskillreborn.item.GearMenuItem;
import net.mcreator.zeldaswordskillreborn.item.ForestMedallionItem;
import net.mcreator.zeldaswordskillreborn.item.FireMedallionItem;
import net.mcreator.zeldaswordskillreborn.item.FairySlingshotItem;
import net.mcreator.zeldaswordskillreborn.item.FairyOcarinaItem;
import net.mcreator.zeldaswordskillreborn.item.EponasongItem;
import net.mcreator.zeldaswordskillreborn.item.EmptyBottleItem;
import net.mcreator.zeldaswordskillreborn.item.DekuStickItem;
import net.mcreator.zeldaswordskillreborn.item.DekuShieldItem;
import net.mcreator.zeldaswordskillreborn.item.DekuSeedItem;
import net.mcreator.zeldaswordskillreborn.item.BowofHeroItem;
import net.mcreator.zeldaswordskillreborn.item.BowOfHerooDrawing3Item;
import net.mcreator.zeldaswordskillreborn.item.BowOfHeroDrawing1Item;
import net.mcreator.zeldaswordskillreborn.item.BowOfHeroDrawin2Item;
import net.mcreator.zeldaswordskillreborn.item.BoomerangItem;
import net.mcreator.zeldaswordskillreborn.item.BombItem;
import net.mcreator.zeldaswordskillreborn.item.BoleroofFireItem;
import net.mcreator.zeldaswordskillreborn.item.BlueRupeeItem;
import net.mcreator.zeldaswordskillreborn.item.BigorronSwordItem;
import net.mcreator.zeldaswordskillreborn.ZeldaSwordSkillRebornMod;

public class ZeldaSwordSkillRebornModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ZeldaSwordSkillRebornMod.MODID);
	public static final RegistryObject<Item> KOKIRI_SWORD = REGISTRY.register("kokiri_sword", () -> new KokiriSwordItem());
	public static final RegistryObject<Item> MASTER_SWORD = REGISTRY.register("master_sword", () -> new MasterSwordItem());
	public static final RegistryObject<Item> BIGORRON_SWORD = REGISTRY.register("bigorron_sword", () -> new BigorronSwordItem());
	public static final RegistryObject<Item> DEKU_SHIELD = REGISTRY.register("deku_shield", () -> new DekuShieldItem());
	public static final RegistryObject<Item> HYLIAN_SHIELD = REGISTRY.register("hylian_shield", () -> new HylianShieldItem());
	public static final RegistryObject<Item> MIRROR_SHIELD = REGISTRY.register("mirror_shield", () -> new MirrorShieldItem());
	public static final RegistryObject<Item> KOKIRI_TUNIC_HELMET = REGISTRY.register("kokiri_tunic_helmet", () -> new KokiriTunicItem.Helmet());
	public static final RegistryObject<Item> KOKIRI_TUNIC_CHESTPLATE = REGISTRY.register("kokiri_tunic_chestplate", () -> new KokiriTunicItem.Chestplate());
	public static final RegistryObject<Item> KOKIRI_TUNIC_LEGGINGS = REGISTRY.register("kokiri_tunic_leggings", () -> new KokiriTunicItem.Leggings());
	public static final RegistryObject<Item> KOKIRI_TUNIC_BOOTS = REGISTRY.register("kokiri_tunic_boots", () -> new KokiriTunicItem.Boots());
	public static final RegistryObject<Item> GORON_TUNIC_HELMET = REGISTRY.register("goron_tunic_helmet", () -> new GoronTunicItem.Helmet());
	public static final RegistryObject<Item> GORON_TUNIC_CHESTPLATE = REGISTRY.register("goron_tunic_chestplate", () -> new GoronTunicItem.Chestplate());
	public static final RegistryObject<Item> GORON_TUNIC_LEGGINGS = REGISTRY.register("goron_tunic_leggings", () -> new GoronTunicItem.Leggings());
	public static final RegistryObject<Item> GORON_TUNIC_BOOTS = REGISTRY.register("goron_tunic_boots", () -> new GoronTunicItem.Boots());
	public static final RegistryObject<Item> ZORA_TUNIC_HELMET = REGISTRY.register("zora_tunic_helmet", () -> new ZoraTunicItem.Helmet());
	public static final RegistryObject<Item> ZORA_TUNIC_CHESTPLATE = REGISTRY.register("zora_tunic_chestplate", () -> new ZoraTunicItem.Chestplate());
	public static final RegistryObject<Item> ZORA_TUNIC_LEGGINGS = REGISTRY.register("zora_tunic_leggings", () -> new ZoraTunicItem.Leggings());
	public static final RegistryObject<Item> ZORA_TUNIC_BOOTS = REGISTRY.register("zora_tunic_boots", () -> new ZoraTunicItem.Boots());
	public static final RegistryObject<Item> FAIRY_SLINGSHOT = REGISTRY.register("fairy_slingshot", () -> new FairySlingshotItem());
	public static final RegistryObject<Item> DEKU_SEED = REGISTRY.register("deku_seed", () -> new DekuSeedItem());
	public static final RegistryObject<Item> BOMB = REGISTRY.register("bomb", () -> new BombItem());
	public static final RegistryObject<Item> BOOMERANG = REGISTRY.register("boomerang", () -> new BoomerangItem());
	public static final RegistryObject<Item> HOOKSHOT = REGISTRY.register("hookshot", () -> new HookshotItem());
	public static final RegistryObject<Item> BOWOF_HERO = REGISTRY.register("bowof_hero", () -> new BowofHeroItem());
	public static final RegistryObject<Item> HAMMER = REGISTRY.register("hammer", () -> new HammerItem());
	public static final RegistryObject<Item> LONGSHOT = REGISTRY.register("longshot", () -> new LongshotItem());
	public static final RegistryObject<Item> HOVER_BOOTS = REGISTRY.register("hover_boots", () -> new HoverItem.Boots());
	public static final RegistryObject<Item> KOKIRI_EMERAULD = REGISTRY.register("kokiri_emerauld", () -> new KokiriEmerauldItem());
	public static final RegistryObject<Item> GORON_RUPEE = REGISTRY.register("goron_rupee", () -> new GoronRupeeItem());
	public static final RegistryObject<Item> ZORAS_SAPPHIRE = REGISTRY.register("zoras_sapphire", () -> new ZorasSapphireItem());
	public static final RegistryObject<Item> LIGHT_MEDALLION = REGISTRY.register("light_medallion", () -> new LightMedallionItem());
	public static final RegistryObject<Item> FOREST_MEDALLION = REGISTRY.register("forest_medallion", () -> new ForestMedallionItem());
	public static final RegistryObject<Item> FIRE_MEDALLION = REGISTRY.register("fire_medallion", () -> new FireMedallionItem());
	public static final RegistryObject<Item> WATER_MEDALLION = REGISTRY.register("water_medallion", () -> new WaterMedallionItem());
	public static final RegistryObject<Item> SHADOW_MEDALLION = REGISTRY.register("shadow_medallion", () -> new ShadowMedallionItem());
	public static final RegistryObject<Item> SPIRIT_MEDAILLION = REGISTRY.register("spirit_medaillion", () -> new SpiritMedaillionItem());
	public static final RegistryObject<Item> FAIRY_OCARINA = REGISTRY.register("fairy_ocarina", () -> new FairyOcarinaItem());
	public static final RegistryObject<Item> OCARINA_OF_TIME = REGISTRY.register("ocarina_of_time", () -> new OcarinaOfTimeItem());
	public static final RegistryObject<Item> EMPTY_BOTTLE = REGISTRY.register("empty_bottle", () -> new EmptyBottleItem());
	public static final RegistryObject<Item> GREEN_RUPEE = REGISTRY.register("green_rupee", () -> new GreenRupeeItem());
	public static final RegistryObject<Item> BLUE_RUPEE = REGISTRY.register("blue_rupee", () -> new BlueRupeeItem());
	public static final RegistryObject<Item> PURPLE_RUPEE = REGISTRY.register("purple_rupee", () -> new PurpleRupeeItem());
	public static final RegistryObject<Item> YELLOW_RUPEE = REGISTRY.register("yellow_rupee", () -> new YellowRupeeItem());
	public static final RegistryObject<Item> SILVER_RUPEE = REGISTRY.register("silver_rupee", () -> new SilverRupeeItem());
	public static final RegistryObject<Item> DEKU_STICK = REGISTRY.register("deku_stick", () -> new DekuStickItem());
	public static final RegistryObject<Item> RUPEE_WALLET = REGISTRY.register("rupee_wallet", () -> new RupeeWalletItem());
	public static final RegistryObject<Item> RED_RUPEE = REGISTRY.register("red_rupee", () -> new RedRupeeItem());
	public static final RegistryObject<Item> BOW_OF_HERO_DRAWING_1 = REGISTRY.register("bow_of_hero_drawing_1", () -> new BowOfHeroDrawing1Item());
	public static final RegistryObject<Item> BOW_OF_HERO_DRAWIN_2 = REGISTRY.register("bow_of_hero_drawin_2", () -> new BowOfHeroDrawin2Item());
	public static final RegistryObject<Item> BOW_OF_HEROO_DRAWING_3 = REGISTRY.register("bow_of_heroo_drawing_3", () -> new BowOfHerooDrawing3Item());
	public static final RegistryObject<Item> GEAR_MENU = REGISTRY.register("gear_menu", () -> new GearMenuItem());
	public static final RegistryObject<Item> ITEM_MENU = REGISTRY.register("item_menu", () -> new ItemMenuItem());
	public static final RegistryObject<Item> ZELDAS_LULLABY = REGISTRY.register("zeldas_lullaby", () -> new ZeldasLullabyItem());
	public static final RegistryObject<Item> SUNSSONG = REGISTRY.register("sunssong", () -> new SunssongItem());
	public static final RegistryObject<Item> SARIASSONG = REGISTRY.register("sariassong", () -> new SariassongItem());
	public static final RegistryObject<Item> EPONASONG = REGISTRY.register("eponasong", () -> new EponasongItem());
	public static final RegistryObject<Item> SONG_OF_TIME = REGISTRY.register("song_of_time", () -> new SongOfTimeItem());
	public static final RegistryObject<Item> SONGOF_STORM = REGISTRY.register("songof_storm", () -> new SongofStormItem());
	public static final RegistryObject<Item> MINUETOF_FOREST = REGISTRY.register("minuetof_forest", () -> new MinuetofForestItem());
	public static final RegistryObject<Item> BOLEROOF_FIRE = REGISTRY.register("boleroof_fire", () -> new BoleroofFireItem());
	public static final RegistryObject<Item> SERENADEOF_WATER = REGISTRY.register("serenadeof_water", () -> new SerenadeofWaterItem());
	public static final RegistryObject<Item> NOCTURNEOF_SHADOW = REGISTRY.register("nocturneof_shadow", () -> new NocturneofShadowItem());
	public static final RegistryObject<Item> REQUIEMOF_SPIRITS = REGISTRY.register("requiemof_spirits", () -> new RequiemofSpiritsItem());
	public static final RegistryObject<Item> PRELUDEOF_LIGHT = REGISTRY.register("preludeof_light", () -> new PreludeofLightItem());
	public static final RegistryObject<Item> LEARN_ZL = block(ZeldaSwordSkillRebornModBlocks.LEARN_ZL, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> LEARN_SS = block(ZeldaSwordSkillRebornModBlocks.LEARN_SS, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> LEARN_SA_S = block(ZeldaSwordSkillRebornModBlocks.LEARN_SA_S, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> LEARN_EPONASONG = block(ZeldaSwordSkillRebornModBlocks.LEARN_EPONASONG, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> LEARN_ST = block(ZeldaSwordSkillRebornModBlocks.LEARN_ST, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> LEARN_ST_S = block(ZeldaSwordSkillRebornModBlocks.LEARN_ST_S, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> ROYAL_FAMILY_BLOCK = block(ZeldaSwordSkillRebornModBlocks.ROYAL_FAMILY_BLOCK, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> BLOCKOF_TIME = block(ZeldaSwordSkillRebornModBlocks.BLOCKOF_TIME, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> GATE_OF_TIME = block(ZeldaSwordSkillRebornModBlocks.GATE_OF_TIME, ZeldaSwordSkillRebornModTabs.TAB_ZSS_EQUIPMENT);
	public static final RegistryObject<Item> TP_MINUET = block(ZeldaSwordSkillRebornModBlocks.TP_MINUET, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> TP_BOLERO = block(ZeldaSwordSkillRebornModBlocks.TP_BOLERO, ZeldaSwordSkillRebornModTabs.TAB_ZSS_MUSIC);
	public static final RegistryObject<Item> IRON_BOOTS_BOOTS = REGISTRY.register("iron_boots_boots", () -> new IronBootsItem.Boots());
	public static final RegistryObject<Item> HIDDENBLOCKBOMB = block(ZeldaSwordSkillRebornModBlocks.HIDDENBLOCKBOMB, ZeldaSwordSkillRebornModTabs.TAB_ZSS_BLOCKS);
	public static final RegistryObject<Item> HIDDENBLOCKMASSE = block(ZeldaSwordSkillRebornModBlocks.HIDDENBLOCKMASSE, ZeldaSwordSkillRebornModTabs.TAB_ZSS_BLOCKS);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
